services:
  - name: qr-code-app
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
